### ISSUE TITLE
Not able to add multiline text with different format in central of pie/donut

### ISSUE THREAD

**Issue by krishnagopalpatidar** [toomuchdesign/react-minimal-pie-chart#223]
### Do you want to request a _feature_ or report a _bug_?

help needed

### What is the current behaviour?
Not able to add multiline text with different format in central of pie/donut. We assigned a div to label property with labelStyle and labelPosition as 0. It works fine if we give one line string value, but doesn't work if we assign div.

### What is the expected behaviour?
As per definition of LabelRenderFunction, it seems to accept ReactElementso it should accept <div> with multiline text in different format. Please find attached image having central text we need.

### Steps to Reproduce the Problem

* lineWidth={10}
* labelPosition={0}
* Required values for label, labelStyle

### Specifications
- Version: 8.2.0
- Platform: React 17.0.2
- Subsystem:

![Pie donut with single central text](https://user-images.githubusercontent.com/42218667/125733098-5084c91d-8e7d-46af-be26-5276844b6b48.JPG)

**Comment by toomuchdesign** [comment]
hi @krishnagopalpatidar
if the output to be styled is provided as `PieChart` children, then it has to render [SVG elements](https://developer.mozilla.org/en-US/docs/Web/SVG/Element), no `div`s or any else DOM elements.

Otherwise you can consider rendering these extra elements as normal DOM elements out of the `PieChart` (finding a proper way to position then).
