### ISSUE TITLE
Adding custom generic labels like in recharts library

### ISSUE THREAD

**Issue by numatay** [toomuchdesign/react-minimal-pie-chart#44]
Hi,
I would like to thank you for the great work on the library. We are currently using **recharts library** to draw a donut chart in our project. It works as expected, but its bundle size is extremely huge for visualizing only donut chart. We decided to move away from it and I was happy to find this library. It has the smallest bundle size among pie chart libraries.

I've tried to implement the same donut chart using **react-minimal-pie-chart library**, but I stuck with the following issue. It seems that rendering of a label is applied to every data item. I have attached our current implementation of the donut chart using recharts.
![Donut chart 1](https://user-images.githubusercontent.com/13784311/56734019-90d89300-6783-11e9-9729-9b613767b877.png)
![Donut chart 2](https://user-images.githubusercontent.com/13784311/56734612-27598400-6785-11e9-8d70-784628eda1c8.png)

1) Is it possible to add generic label outside of the chart that is rendered only once? (refer to the 1st rectangle on the picture)
2) Is it possible to add a generic label in the middle of the chart that is rendered only once? ( refer to the 2nd rectangle on the picture) 
3) For some reason, I cannot add `stroke` property to donut segment on the chart. Is it possible to do it in the current release of the library
4) I have tested animation feature on IE11 browser and it doesn't work. Are there any solutions to make it work in IE11?

**Comment by toomuchdesign** [comment]
Hi @numatay,
1) Any generic statically positioned label/element can be easily implemented in userland in your project.
2) See above
3) Chart's segments are actually single SVG paths with an auto calculated stroke attribute applied. Since `stroke` property is what's actually visualised, there's no native way to render borders around segments. You might try and render a second underlying donut below with the border's color. I planned a "Background segment" feature which might have come to help, but never been sure it's really worth the extra complexity.
4) No specific solutions currently available for IE11. Did you get what's actually not working with animations on IE11?

**Comment by numatay** [comment]
Hi @toomuchdesign,

Thank you for the quick reply. Regarding IE11, I tested the animation feature with duration value 2000ms. It does not ease-out and segments move abruptly.
